ruby-dev:
  host: <%= ENV['IMAP_HOST'] %>
  port: <%= ENV['IMAP_PORT'] %>
  username: <%= ENV['IMAP_USERNAME'] %>
  password: "<%= ENV['IMAP_PASSWORD'] %>"

ruby-core:
  host: <%= ENV['IMAP_HOST'] %>
  port: <%= ENV['IMAP_PORT'] %>
  username: <%= ENV['IMAP_USERNAME'] %>
  password: "<%= ENV['IMAP_PASSWORD'] %>"
